### ISSUE TITLE
String builder for better performance?

### ISSUE THREAD

**Issue by jordan-wong** [kyleotero/infinite-monkeys#1]
Possibly experiment with using a string builder instead? Might matter especially when doing billions of concatenations, and memory allocations for repeated new strings might be inefficient but idk how Go does strings
https://github.com/kyleotero/infinite-monkeys/blob/388e792bb7683212e77ed8dce3a09f06cb6f126d/main.go#L80

**Comment by kyleotero** [comment]
Thanks Jordan, will take a look when I have time.

**Comment by kyleotero** [comment]
Updated with a different approach, completely removing strings.
